[project]
name = "demo-creds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.2.6",
    "anthropic>=0.49.0",
    "boto3>=1.37.23",
    "openai>=1.69.0",
]
